Add cuewNvrtcInit() and cuewNvrtcVersion(), refactor generator code
CudaWrangler/cuew pull request #5
Opened 2018-02-06 22:19 UTC by brechtvl

These new functions can be called to use nvrtc without CUDA hardware available, since `cuewInit()` can fail if that's not the case.

Changing the generator code to add these was a pain though. Instead I've made that code use cuew.template.c/h files. These are easier to edit, inserting autogenerated code in a few places rather than generating all C code through Python.

2018-02-06 22:33 UTC, brechtvl commented
I forgot to mention: this also updates the nvrtc dll names, and part of this patch was written by @LazyDodo.

2018-02-07 08:22 UTC, Nazg-Gul commented
Part related on the template is something which will become handy in the future.

But part of split `cuewInit()` and `cuewNvrtcInit()` i didn't quite understand. We don't require hardware, and only requirement i see is CUDA driver version to be 4.0 at least. I don't think older drivers had NVRCT in them, and how is it possible that you have NVRTC without newer driver installed? Has it became part of display driver instead?

To me it seems we should have single `cuewInit()` function which will initialize all available wranglers. If it is REALLY needed to specify which parts we want to ignore, make it a bitmask argument to it.

Put all this information into a commit message. Having such a brief oneliners do not help at all. Also, don't use fullstop in commit subject (first line of commit message).

2018-02-07 08:24 UTC, sergeyvfx requested changes
More information needed, see the comment in conversation.

2018-02-07 09:19 UTC, brechtvl commented
`libcuda` is part of the driver, and `dlopen()` on it fails there is no CUDA hardware. And `libnvrtc` can be installed as part of the CUDA toolkit, without the driver.

If we add a argument to `cuewInit()`, we break backwards compatibility. I wouldn't mind doing that though, because I think it's bad that we are now automatically loading `libnvrtc` along with `libcuda`. Most of the time there is no reason to have the time and memory overhead of loading the compiler when all you need to do is render something.

2018-02-07 09:31 UTC, Nazg-Gul commented
> What we are interested is loading libnvrtc to compile programs without having any CUDA hardware.

What is the usecase for that?

> If we add a argument to cuewInit(), we break backwards compatibility.

You break it anyway by removing NVRTC library load from `cuewInit()`. So everyone will need to change their programs anyway. I also not sure we ever declared API stable. We didn't even make a release or anything..

If you are really worried about compatibility, it's possible to keep compatibility by doing some variadic macro, which will convert `cuewInit()` to a call with both CUDA and NVRTC requested for load. But i don't think it worth it.

> Most of the time there is no reason to have the time and memory overhead of loading the compiler when all you need to do is render something.

Did you quantify memory and time? Is it really that bad?

2018-02-07 09:56 UTC, brechtvl commented
> What is the usecase for that?

Compiling CUDA binaries for Blender releases: https://developer.blender.org/D3045

> Did you quantify memory and time? Is it really that bad?

No, I did not quantify it, and it may not be bad in practice. But it's a big library, it might be doing a bunch of static initialization, and these things can change over time. It's just an argument in favor or breaking backwards compatibility, which you already seem to agree with so it doesn't matter.

2018-02-07 10:04 UTC, Nazg-Gul commented
> Compiling CUDA binaries for Blender releases: https://developer.blender.org/D3045

Makes sense. But all such usecases are to be reflected in clear explanatory commit message.

> No, I did not quantify it, and it may not be bad in practice. But it's a big library, it might be doing a bunch of static initialization, and these things can change over time. It's just an argument in favor or breaking backwards compatibility, which you already seem to agree with so it doesn't matter.

Yes, make it a bitmask argument to cuewInit(). Internally you can still split the function up, to avoid too long of a function which does everything.

2018-02-07 10:05 UTC, brechtvl commented
Updated with flags for `cuewInit()`, version bump to indicate compatibility breakage, and better commit messages.

2018-02-07 10:08 UTC, sergeyvfx requested changes

2018-02-07 10:08 UTC, Nazg-Gul commented on auto/cuew.template.c
> +int cuewNvrtcInit(void) {
Seems to be private function which is not exposed to a public API. Hence should be using static qualifier.

2018-02-07 10:17 UTC, brechtvl commented
Made function static.

2018-02-07 10:18 UTC, sergeyvfx approved these changes
Think we are good now.

Do you have commit access here?

2018-02-07 10:21 UTC, brechtvl commented
No, I wouldn't mind getting it though.

2018-02-07 10:27 UTC, merged